### ISSUE TITLE
Rails/SkipsModelValidations

### ISSUE THREAD

**Issue by xredo** [MarsBased/marstyle#4]
This is the original definition:

```yaml
Rails/SkipsModelValidations:
  Blacklist:
    - decrement!
    - decrement_counter
    - increment!
    - increment_counter
    - toggle!
    - touch
    - update_all
    - update_attribute
    - update_column
    - update_columns
    - update_counters
```

This prevents us to use update_column, or update_all, which are methods that I find useful for performance optimization and certain situations.
